#!/bin/bash

# Finds the sum in a file composed of numbers

if [ $# -gt 1 ]; then
  echo "Improper invocation: supply either no parameters (to read from the stdin) or one parameter -- the input filename."
  exit 129
fi

if [ $# -eq 1 ]; then
  filename="$1"
else
  filename="/dev/stdin"
fi

cat "$filename" | awk 'BEGIN{sum=0;} {for(i=1;i<=NF;++i) {sum+=$i;}} END{print sum}'

