#!/bin/bash
##########################################################################################
# Takes a pdb file as input and creates a pdb file containing a translated version
#
# v1.00 2010.02.10 jd, first version
# v1.10 2010.03.24 jd, warns if input file malformed
# v1.15 2010.06.30 jd, translates HETATM records as well
##########################################################################################
##########################################################################################

ver="1.15"

##########################################################################################

echo "" >&2
echo "*** pdbtranslate v$ver. Translates the atoms inside a pdb file." >&2
echo "                        2010.02.10 Jacek Dziedzic, jack.erede@gmail.com" >&2
echo "" >&2

if [ $# -ne 4 ]; then
  echo "Supply four arguments -- name of the input pdb file, and three Cartesian coordinates of the translation vector. Aborting!" >&2
  exit 101
fi

f=$1
x=$2
y=$3
z=$4

if [ ! -r "$f" ]; then
  echo "$f not readable. Aborting!" >&2
  exit 102
fi

cat $f | awk -v x=$x -v y=$y -v z=$z '
                     {
                       if($1=="ATOM" || $1=="HETATM") {
                         # Must replace the coordinates at exactly the same spot, becase PDB is picky about formatting :(
                         line=$0;
			 xx=substr(line,32,7);
			 newx=sprintf("%8.3f",xx+x)
			 yy=substr(line,40,7);
			 newy=sprintf("%8.3f",yy+y)
			 zz=substr(line,48,7);
			 newz=sprintf("%8.3f",zz+z)
			 newline=substr(line,1,30) newx newy newz substr(line,55)
			 print newline			 
                         if(substr(xx,7,1)==" " || substr(yy,7,1)==" " || substr(zz,7,1)==" ") 
                           printf("Malformed .pdb file (horizontal formatting broken, might lead to breakage!)\n") > "/dev/stderr";
		       }
		       else print $0;
		     }
              '
